version: '3.7'

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'mongoLogin'
      MONGO_INITDB_ROOT_PASSWORD: 'mongoPassword'
      MONGO_INITDB_DATABASE: 'tokens'
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
